export const SET_CURRENT_BU = "bu.SET_CURRENT_BU"
export const SET_BU = "bu.SET_BU"
export const RESET_CURRENT_BU = "bu.RESET_CURRENT_BU"
export const UPDATE_CURRENT_BU = "bu.UPDATE_CURRENT_BU"
export const SET_EDIT_BU = "bu.SET_EDIT_BU"
