export const SET_CURRENT_DO = "Do.SET_CURRENT_DO"
export const SET_DO = "Do.SET_DO"
export const RESET_CURRENT_DO = "Do.RESET_CURRENT_DO"
export const UPDATE_CURRENT_DO = "Do.UPDATE_CURRENT_DO"
export const SET_EDIT_DO = "Do.SET_EDIT_DO"