export const SET_CURRENT_EXP = "exp.SET_CURRENT_EXP"
export const SET_EXP = "exp.SET_EXP"
export const RESET_CURRENT_EXP = "exp.RESET_CURRENT_EXP"
export const UPDATE_CURRENT_EXP = "exp.UPDATE_CURRENT_EXP"
export const SET_EDIT_EXP = "exp.SET_EDIT_EXP"