export const SET_CURRENT_INC = "inc.SET_CURRENT_INC"
export const SET_INC = "inc.SET_INC"
export const RESET_CURRENT_INC = "inc.RESET_CURRENT_INC"
export const UPDATE_CURRENT_INC = "inc.UPDATE_CURRENT_INC"
export const SET_EDIT_INC = "inc.SET_EDIT_INC"