export const SET_CURRENT_INV = "inv.SET_CURRENT_INV"
export const SET_INV = "inv.SET_INV"
export const RESET_CURRENT_INV = "inv.RESET_CURRENT_INV"
export const UPDATE_CURRENT_INV = "inv.UPDATE_CURRENT_INV"
export const SET_EDIT_INV = "inv.SET_EDIT_INV"