export const SET_CURRENT_INV = "inv.SET_CURRENT_INV"
export const SET_INV = "inv.SET_INV"
export const RESET_CURRENT_INV = "inv.RESET_CURRENT_INV"
export const UPDATE_CURRENT_INV = "inv.UPDATE_CURRENT_INV"
export const SET_EDIT_INV = "inv.SET_EDIT_INV"

export const SET_CURRENT_PB_FK = "fk_pb.SET_CURRENT_PB_FK"
export const SET_PB_FK = "fk_pb.SET_PB_FK"
export const RESET_CURRENT_PB_FK = "fk_pb.RESET_CURRENT_PB_FK"
export const UPDATE_CURRENT_PB_FK = "fk_pb.UPDATE_CURRENT_PB_FK"
export const SET_EDIT_PB_FK = "fk_pb.SET_EDIT_PB_FK"

export const SET_CURRENT_FK = "fk_pj.SET_CURRENT_FK"
export const SET_FK = "fk_pj.SET_FK"
export const RESET_CURRENT_FK = "fk_pj.RESET_CURRENT_FK"
export const UPDATE_CURRENT_FK = "fk_pj.UPDATE_CURRENT_FK"
export const SET_EDIT_FK = "fk_pj.SET_EDIT_FK"

export const SET_CURRENT_INVPJ = "inv_pj.SET_CURRENT_INVPJ"
export const SET_INVPJ = "inv_pj.SET_INVPJ"
export const RESET_CURRENT_INVPJ = "inv_pj.RESET_CURRENT_INVPJ"
export const UPDATE_CURRENT_INVPJ = "inv_pj.UPDATE_CURRENT_INVPJ"
export const SET_EDIT_INVPJ = "inv_pj.SET_EDIT_INVPJ"