export const SET_CURRENT_KH = "kh.SET_CURRENT_KH"
export const SET_KH = "kh.SET_KH"
export const RESET_CURRENT_KH = "kh.RESET_CURRENT_KH"
export const UPDATE_CURRENT_KH = "kh.UPDATE_CURRENT_KH"
export const SET_EDIT_KH = "kh.SET_EDIT_KH"