export const SET_CURRENT_KP = "kp.SET_CURRENT_KP"
export const SET_KP = "kp.SET_KP"
export const RESET_CURRENT_KP = "kp.RESET_CURRENT_KP"
export const UPDATE_CURRENT_KP = "kp.UPDATE_CURRENT_KP"
export const SET_EDIT_KP = "kp.SET_EDIT_KP"