export const SET_CURRENT_OUT = "out.SET_CURRENT_OUT"
export const SET_OUT = "out.SET_OUT"
export const RESET_CURRENT_OUT = "out.RESET_CURRENT_OUT"
export const UPDATE_CURRENT_OUT = "out.UPDATE_CURRENT_OUT"
export const SET_EDIT_OUT = "out.SET_EDIT_OUT"