export const SET_CURRENT_PB = "pb.SET_CURRENT_PB"
export const SET_PB = "pb.SET_PB"
export const RESET_CURRENT_PB = "pb.RESET_CURRENT_PB"
export const UPDATE_CURRENT_PB = "pb.UPDATE_CURRENT_PB"
export const SET_EDIT_PB = "pb.SET_EDIT_PB"