export const SET_CURRENT_PBB = "pbb.SET_CURRENT_PBB"
export const SET_PBB = "pbb.SET_PBB"
export const RESET_CURRENT_PBB = "pbb.RESET_CURRENT_PBB"
export const UPDATE_CURRENT_PBB = "pbb.UPDATE_CURRENT_PBB"
export const SET_EDIT_PBB = "pbb.SET_EDIT_PBB"