export const SET_CURRENT_PHJ = "phj.SET_CURRENT_PHJ"
export const SET_PHJ = "phj.SET_PHJ"
export const RESET_CURRENT_PHJ = "phj.RESET_CURRENT_PHJ"
export const UPDATE_CURRENT_PHJ = "phj.UPDATE_CURRENT_PHJ"
export const SET_EDIT_PHJ = "phj.SET_EDIT_PHJ"