export const SET_CURRENT_PL = "plan.SET_CURRENT_PL"
export const SET_PL = "plan.SET_PL"
export const RESET_CURRENT_PL = "plan.RESET_CURRENT_PL"
export const UPDATE_CURRENT_PL = "plan.UPDATE_CURRENT_PL"
export const SET_EDIT_PL = "plan.SET_EDIT_PL"