export const SET_CURRENT_PO = "po.SET_CURRENT_PO"
export const SET_PO = "po.SET_PO"
export const RESET_CURRENT_PO = "po.RESET_CURRENT_PO"
export const UPDATE_CURRENT_PO = "po.UPDATE_CURRENT_PO"
export const SET_EDIT = "po.SET_EDIT"