export const SET_PRODUCT = "product.SET_PRODUCT"
export const SET_ORIGINAL_PRODUCT = "product.SET_ORIGINAL_PRODUCT"
export const SET_FILTER_PRODUCT = "product.SET_FILTER_PRODUCT"
export const SET_APPLY_FILTER_PRODUCT = "product.SET_APPLY_FILTER_PRODUCT"