export const SET_CURRENT_RB = "rb.SET_CURRENT_RB"
export const SET_RB = "rb.SET_RB"
export const RESET_CURRENT_RB = "rb.RESET_CURRENT_RB"
export const UPDATE_CURRENT_RB = "rb.UPDATE_CURRENT_RB"
export const SET_EDIT_RB = "rb.SET_EDIT_RB"