export const SET_CURRENT_RP = "rp.SET_CURRENT_RP"
export const SET_RP = "rp.SET_RP"
export const RESET_CURRENT_RP = "rp.RESET_CURRENT_RP"
export const UPDATE_CURRENT_RP = "rp.UPDATE_CURRENT_RP"
export const SET_EDIT = "rp.SET_EDIT"

export const SET_CURRENT_RP_AUTO = "rp_auto.SET_CURRENT_RP_AUTO"
export const SET_RP_AUTO = "rp_auto.SET_RP_AUTO"
export const RESET_CURRENT_RP_AUTO = "rp_auto.RESET_CURRENT_RP_AUTO"
export const UPDATE_CURRENT_RP_AUTO = "rp_auto.UPDATE_CURRENT_RP_AUTO"
export const SET_EDIT_AUTO = "rp_auto.SET_EDIT_AUTO"