export const SET_CURRENT_RP = "rp.SET_CURRENT_RP"
export const SET_RP = "rp.SET_RP"
export const RESET_CURRENT_RP = "rp.RESET_CURRENT_RP"
export const UPDATE_CURRENT_RP = "rp.UPDATE_CURRENT_RP"
export const SET_EDIT = "rp.SET_EDIT"