export const SET_CURRENT_SO = "so.SET_CURRENT_SO"
export const SET_SO = "so.SET_SO"
export const RESET_CURRENT_SO = "so.RESET_CURRENT_SO"
export const UPDATE_CURRENT_SO = "so.UPDATE_CURRENT_SO"
export const SET_EDIT_SO = "so.SET_EDIT"